FROM alpine:3.13
<error descr="Multiple HEALTHCHECK defined
Providing more than one HEALTHCHECK instruction per stage is confusing and error-prone.">HEALTHCHECK CMD /bin/healthcheck</error>
HEALTHCHECK CMD /bin/healthcheck
USER mike
CMD ./app
