FROM ubuntu:18.04
<warning descr="'RUN <package-manager> update' instruction alone
The instruction 'RUN <package-manager> update' should always be followed by '<package-manager> install' in the same RUN statement.">RUN apt-get update</warning>
RUN apt-get install -y --no-install-recommends mysql-client     && rm -rf /var/lib/apt/lists/* && apt-get clean
USER mike
ENTRYPOINT mysql