FROM alpine:3.5
<warning descr="'yum clean all' missing
You should use 'yum clean all' after using a 'yum install' command to clean package cached data and reduce image size.">RUN yum install -y vim</warning>
USER mike