FROM alpine:3.5
<warning descr="'yum clean all' missing
You should use 'yum clean all' after using a 'yum install' command to clean package cached data and reduce image size.">RUN yum install vim</warning>
RUN pip install --no-cache-dir -r /usr/src/app/requirements.txt
USER mike
CMD python /usr/src/app/app.py