<error descr="':latest' tag used
When using image you should use a specific tag to avoid uncontrolled behavior when the image is updated.">FROM debian:latest</error>
RUN apt-get update && apt-get -y install vim && apt-get clean
USER foo
