FROM alpine:3.13
USER mike
<error descr="Exposed port 65536 out of range
UNIX ports outside the range 0-65535 are exposed."><error descr="Exposed port 65537 out of range
UNIX ports outside the range 0-65535 are exposed.">EXPOSE 65536 65537</error></error>
