FROM alpine:3.13
USER mike
ADD "/target/resources.tar.gz" "resources.jar"
<error descr="ADD instead of COPY
You should use COPY instead of ADD unless you want to extract a tar file.">ADD "/target/app.jar" "app.jar"</error>
COPY target.zip target-1.zip
<error descr="ADD instead of COPY
You should use COPY instead of ADD unless you want to extract a tar file.">ADD "/target/app.jar" "/target/app2.jar" "app/"</error>
<error descr="ADD instead of COPY
You should use COPY instead of ADD unless you want to extract a tar file.">ADD ["/target/app.jar","/target/app3.jar","app/"]</error>
<error descr="ADD instead of COPY
You should use COPY instead of ADD unless you want to extract a tar file.">ADD ["/target/app.jar","app/"]</error>
