FROM alpine:3.13
USER mike
ADD "/target/resources.tar.gz" "resources.jar"
<warning descr="ADD instead of COPY
You should use COPY instead of ADD unless you want to extract a tar file.">ADD "/target/app.jar" "app.jar"</warning>
COPY target.zip target-1.zip