FROM debian:9.13
<warning descr="'apt-get dist-upgrade' used
'apt-get dist-upgrade' upgrades a major version so it doesn't make more sense in Dockerfile.">RUN ["apt-get", "dist-upgrade"]</warning>
USER mike
CMD python /usr/src/app/app.py
