FROM golang:1.7.3 as dep
COPY dep /binary /
<warning descr="Multiple ENTRYPOINT instructions listed
There can only be one ENTRYPOINT instruction in a Dockerfile.">ENTRYPOINT [ "/opt/app/run.sh --port 8080" ]</warning>
ENTRYPOINT [ "/opt/app/run.sh --port 8080" ]

FROM alpine:3.13
USER mike
ENTRYPOINT [ "/opt/app/run.sh --port 8080" ]