FROM baseImage:1.1
RUN test

FROM debian:jesse2 as build
USER mike
RUN stuff

FROM debian:jesse1 <warning descr="Duplicate aliases defined in different FROMs
Different FROMs can't have the same alias defined.">as build</warning>
USER mike
RUN more_stuff